// =========================
// FORM SUBMIT
// =========================

document
  .getElementById("patientForm")
  .addEventListener("submit", async function (e) {

    e.preventDefault();

    // =========================
    // INPUTS
    // =========================

    const name =
      document.getElementById("patientName").value;

    const age =
      document.getElementById("patientAge").value;

    const gender =
      document.getElementById("patientGender").value;

    const imageInput =
      document.getElementById("mriImage");

    const file =
      imageInput.files[0];

    const submitBtn =
      document.getElementById("submitBtn");

    // =========================
    // VALIDATION
    // =========================

    if (!file) {

      alert("Please upload MRI image.");

      return;
    }

    // =========================
    // SHOW PATIENT INFO
    // =========================

    document.getElementById("reportName")
      .innerText = name;

    document.getElementById("reportAge")
      .innerText = age;

    document.getElementById("reportGender")
      .innerText = gender;

    // =========================
    // IMAGE PREVIEW
    // =========================

    const reader = new FileReader();

    reader.onload = function (e) {

      const img =
        document.getElementById("previewImage");

      img.src = e.target.result;

      img.style.display = "block";
    };

    reader.readAsDataURL(file);

    // =========================
    // LOADING STATE
    // =========================

    document.getElementById("reportResult")
      .innerText = "Analyzing MRI Scan...";

    document.getElementById("reportConfidence")
      .innerText = "Processing...";

    // Disable button
    submitBtn.disabled = true;

    submitBtn.innerText = "Analyzing...";

    // =========================
    // SEND DATA
    // =========================

    const formData = new FormData();

    formData.append("image", file);

    try {

      const response = await fetch(
        "/predict",
        {
          method: "POST",
          body: formData
        }
      );

      // =========================
      // CHECK RESPONSE
      // =========================

      if (!response.ok) {

        throw new Error(
          "Failed to connect server"
        );
      }

      const data = await response.json();

      console.log(data);

      // =========================
      // HANDLE BACKEND ERROR
      // =========================

      if (data.error) {

        document.getElementById("reportResult")
          .innerText = "Prediction Failed";

        document.getElementById("reportConfidence")
          .innerText = data.error;

        return;
      }

      // =========================
      // SHOW RESULT
      // =========================

      document.getElementById("reportResult")
        .innerText = data.prediction;

      document.getElementById("reportConfidence")
        .innerText = data.confidence + "%";

    }

    catch (error) {

      console.error(error);

      document.getElementById("reportResult")
        .innerText = "Server Error";

      document.getElementById("reportConfidence")
        .innerText = error.message;
    }

    finally {

      // Enable button again

      submitBtn.disabled = false;

      submitBtn.innerText = "Analyze MRI";
    }

  });


// =========================
// PDF DOWNLOAD
// =========================

async function downloadPDF() {

  const result =
    document.getElementById("reportResult").innerText;

  if (
    result === "" ||
    result === "Analyzing MRI Scan..." ||
    result === "Server Error"
  ) {

    alert(
      "Please generate report first."
    );

    return;
  }

  const { jsPDF } = window.jspdf;

  const doc = new jsPDF();

  // =========================
  // GET VALUES
  // =========================

  const name =
    document.getElementById("reportName").innerText;

  const age =
    document.getElementById("reportAge").innerText;

  const gender =
    document.getElementById("reportGender").innerText;

  const confidence =
    document.getElementById("reportConfidence").innerText;

  // =========================
  // TITLE
  // =========================

  doc.setFontSize(22);

  doc.text(
    "Brain Tumor Detection Report",
    20,
    20
  );

  // =========================
  // REPORT DETAILS
  // =========================

  doc.setFontSize(14);

  doc.text(`Patient Name: ${name}`, 20, 50);

  doc.text(`Age: ${age}`, 20, 65);

  doc.text(`Gender: ${gender}`, 20, 80);

  doc.text(`Detection Result: ${result}`, 20, 95);

  doc.text(`Confidence: ${confidence}`, 20, 110);

  doc.text(
    "Generated By AI CNN Detection System",
    20,
    140
  );

  // =========================
  // SAVE PDF
  // =========================

  doc.save("Brain_Tumor_Report.pdf");
}